Repository hashicorp/terraform-provider-external, pull requests merged in 2022-03, with the labels that each got.

#117 GH Action to link incoming issues and pull-requests to the Terraform DevEx Team board
  .github/workflows/add-content-to-project.yml
Labels: size/S

#118 docs: Remove legacy sidebar features
  website/docs/data_source.html.md
  website/docs/index.html.markdown
  website/external.erb
Labels: documentation, size/XS

#120 Update GH Action 'add-content-to-project' to use 'pull_request_target' to allow access to project secrets
  .github/workflows/add-content-to-project.yml
Labels: size/XS

#122 Update CODEOWNERS with new team name: @hashicorp/terraform-devex
  .github/CODEOWNERS
Labels: size/XS

#119 data-source/external: Prevent panics with empty program arguments
  internal/provider/data_source.go
  internal/provider/data_source_test.go
Labels: bug, crash, size/M
