Repository hashicorp/terraform-provider-external, pull requests merged in 2023-03, with the labels that each got.

#184 Migrate to Terraform Plugin Framework
  .changes/unreleased/NOTES-20230227-115045.yaml
  .github/CODE_OF_CONDUCT.md
  .github/SUPPORT.md
  .github/workflows/test.yml
  .golangci.yml
  DESIGN.md
  GNUmakefile
  README.md
  docs/data-sources/external.md
  docs/index.md
  examples/data-sources/external.tf
  examples/json-processing.sh
  go.mod
  go.sum
  internal/provider/data_source.go
  internal/provider/data_source_test.go
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/test-programs/tf-acc-external-data-source/main.go
  main.go
  scripts/changelog-links.sh
  scripts/errcheck.sh
  scripts/gofmtcheck.sh
  scripts/gogetcookie.sh
  templates/data-sources/external.md.tmpl
  templates/index.md.tmpl
  tools/tools.go
  website/docs/data_source.html.md
Labels: documentation, dependencies, size/XL

#189 Update release workflow to use service account PAT
  .github/workflows/release.yml
Labels: size/S

#194 Remove filter for empty and null query values
  .changes/unreleased/BUG FIXES-20230306-143852.yaml
  internal/provider/data_source.go
  internal/provider/data_source_test.go
  internal/provider/test-programs/tf-acc-external-data-source/main.go
Labels: size/XS

#196 .github/workflows: Test on Terraform 1.4.* versions
  .github/workflows/test.yml
Labels: size/XS

#192 Updating to Go 1.19
  .changes/unreleased/NOTES-20230303-143616.yaml
  README.md
  go.mod
  internal/provider/data_source.go
  internal/provider/data_source_test.go
Labels: dependencies, size/M, go
